sudo: false

dist: trusty

language: java

jdk: oraclejdk8

cache:
  directories:
    - "$HOME/.m2/repository"

install:
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] || [[ $TRAVIS_TAG = v* ]]; then GOAL=deploy; else GOAL=install; fi

script: mvn -q -U -T 2 install

notifications:
  slack:
    secure: $SLACK_INTEGRATION